# Generated by Django 5.0.1 on 2024-04-16 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_car_current_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wheels', models.IntegerField()),
                ('car_type', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=50)),
                ('clutch', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=10)),
                ('kilometrage', models.IntegerField()),
                ('offering_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile', verbose_name='name of current user of this car')),
            ],
        ),
    ]
