# Generated by Django 5.0.1 on 2024-04-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wheels', models.IntegerField()),
                ('car_type', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=50)),
                ('clutch', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=10)),
                ('kilometrage', models.IntegerField()),
            ],
        ),
    ]
