# Generated by Django 5.0.1 on 2024-04-14 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_car_current_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='current_user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='core.profile', verbose_name='name of current user of this car'),
        ),
    ]
